development:
  adapter: postgresql
  database: railsblog_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: railsblog_test
  pool: 5
  timeout: 5000
production:
  adapter: postgresql
  database: railsblog
  username: adminb4ld6dy
  password: BiV4G7KF_9Up
  pool: 5
  timeout: 5000
